spring:
  h2:
    console:
      enabled: true
      path: '/console'

  main:
    banner-mode: "off"

  datasource:
    url: 'jdbc:h2:file:./spring-boot-h2-db'
    username: 'sa'
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

task:
  template:
    allow-multiple-task: false


